import { describe, it, expect, vi, beforeEach } from 'vitest'
import {
  mentalHealthToMarkdown,
  pgxToMarkdown,
  riskLandscapeToMarkdown,
  addictionToMarkdown,
  geneToMarkdown,
  checklistToMarkdown,
} from '../lib/export'
import type { PathwaySection, ActionData } from '../types/genomics'
import type { PGxEnzymeSection } from '../types/pgx'
import type { ChecklistItem } from '../hooks/useChecklist'

// Freeze date so footer is deterministic
beforeEach(() => {
  vi.useFakeTimers()
  vi.setSystemTime(new Date('2026-01-15'))
})

// ── mentalHealthToMarkdown ──────────────────────────────────────────────────

describe('mentalHealthToMarkdown', () => {
  const sections: PathwaySection[] = [{
    narrative: {
      pathway: 'Methylation',
      status: 'actionable',
      body: 'Reduced folate conversion detected.',
      priority: '1 actionable',
      hint: '',
      geneCount: 1,
      actionCount: 1,
    },
    genes: [{
      symbol: 'MTHFR', variant: 'C677T', rsid: 'rs1801133',
      genotype: 'T/T', status: 'actionable', evidenceTier: 'E2',
      studyCount: 12, description: 'Reduced folate conversion.',
      actionCount: 1, categories: ['mood'], pathway: 'Methylation',
    }],
  }]

  const actions: Record<string, ActionData[]> = {
    MTHFR: [{
      id: 'a1', type: 'consider', title: 'Take methylfolate',
      description: 'Bypasses MTHFR.', evidenceTier: 'E2',
      studyCount: 12, tags: ['supplement'], geneSymbol: 'MTHFR', done: false,
    }],
  }

  it('includes header and date', () => {
    const md = mentalHealthToMarkdown(sections, actions)
    expect(md).toContain('# Mental Health Genetic Profile')
    expect(md).toContain('2026-01-15')
  })

  it('includes pathway heading and narrative', () => {
    const md = mentalHealthToMarkdown(sections, actions)
    expect(md).toContain('## Methylation')
    expect(md).toContain('Reduced folate conversion detected.')
  })

  it('renders gene table with correct columns', () => {
    const md = mentalHealthToMarkdown(sections, actions)
    expect(md).toContain('| MTHFR | C677T | T/T | actionable | E2 (12 sources) |')
  })

  it('renders actions as checklist items', () => {
    const md = mentalHealthToMarkdown(sections, actions)
    expect(md).toContain('- [ ] **CONSIDER**: Take methylfolate')
  })

  it('marks done actions with [x]', () => {
    const doneActions = { MTHFR: [{ ...actions.MTHFR[0], done: true }] }
    const md = mentalHealthToMarkdown(sections, doneActions)
    expect(md).toContain('- [x] **CONSIDER**: Take methylfolate')
  })

  it('includes footer', () => {
    const md = mentalHealthToMarkdown(sections, actions)
    expect(md).toContain('Generated by Genome Toolkit')
  })
})

// ── pgxToMarkdown ───────────────────────────────────────────────────────────

describe('pgxToMarkdown', () => {
  const sections: PGxEnzymeSection[] = [{
    enzyme: {
      symbol: 'CYP2D6', alleles: '*1/*4', status: 'intermediate',
      position: 30, description: 'Reduced metabolism.',
      guideline: 'CPIC', geneType: 'enzyme',
    },
    drugs: [{
      drugClass: 'SSRIs', impact: 'adjust', statusText: 'May need dose adjustment',
      description: 'Lower starting dose recommended.', drugList: 'fluoxetine, paroxetine',
      category: 'prescription', evidenceScope: 'guideline',
    }],
  }]

  it('includes header and disclaimer', () => {
    const md = pgxToMarkdown(sections)
    expect(md).toContain('# PGx / Drug Metabolism Report')
    expect(md).toContain('Discuss all changes with your prescribing physician')
  })

  it('renders enzyme section with status', () => {
    const md = pgxToMarkdown(sections)
    expect(md).toContain('## CYP2D6 — INTERMEDIATE metabolizer')
    expect(md).toContain('**Genotype:** *1/*4')
    expect(md).toContain('**Guideline:** CPIC')
  })

  it('renders drug cards with impact marker', () => {
    const md = pgxToMarkdown(sections)
    expect(md).toContain('### ! SSRIs [ADJUST]')
    expect(md).toContain('**Drugs affected:** fluoxetine, paroxetine')
  })

  it('renders danger notes as warnings', () => {
    const dangerSections: PGxEnzymeSection[] = [{
      ...sections[0],
      drugs: [{
        ...sections[0].drugs[0],
        impact: 'danger',
        dangerNote: 'Avoid codeine completely.',
      }],
    }]
    const md = pgxToMarkdown(dangerSections)
    expect(md).toContain('### !!! SSRIs [DANGER]')
    expect(md).toContain('> **WARNING:** Avoid codeine completely.')
  })

  it('segregates non-guideline/label scopes out of the prescriber report body', () => {
    const mixed: PGxEnzymeSection[] = [{
      ...sections[0],
      drugs: [
        { ...sections[0].drugs[0], drugClass: 'SSRIs', evidenceScope: 'guideline' },
        {
          drugClass: 'Ketamine', impact: 'warn', statusText: 'Avoid combos',
          description: 'Harm-reduction note.', drugList: 'ketamine',
          category: 'substance', evidenceScope: 'harm_reduction',
          dangerNote: 'Never combine with alcohol or benzos.',
        },
      ],
    }]
    const md = pgxToMarkdown(mixed)
    // Guideline-scoped drug stays in the prescriber report.
    expect(md).toContain('SSRIs')
    // Harm-reduction content is KEPT (not removed) ...
    expect(md).toContain('Ketamine')
    expect(md).toContain('Never combine with alcohol or benzos.')
    // ... but explicitly flagged as not-for-prescribing / not genotype-backed.
    expect(md).toMatch(/Not genotype-backed dosing|not for prescribing/i)
  })
})

// ── riskLandscapeToMarkdown ─────────────────────────────────────────────────

describe('riskLandscapeToMarkdown', () => {
  const causes = [{
    rank: 1, cause: 'Heart Disease', pct: 23.0,
    populationBarPct: 100, personalBarPct: 80,
    status: 'actionable' as const, genesText: 'APOE, MTHFR',
    statusText: 'Actionable',
    narrative: 'Elevated risk due to APOE variant.',
    genes: [{ symbol: 'APOE', variant: 'E3/E4', evidenceTier: 'E1', status: 'actionable' as const, description: 'Increased LDL.' }],
    actions: [{ type: 'consider' as const, text: 'Statins discussion' }],
  }]

  it('renders table with all causes', () => {
    const md = riskLandscapeToMarkdown(causes)
    expect(md).toContain('| 1 | Heart Disease | 23% | actionable | APOE, MTHFR |')
  })

  it('expands causes with genes and actions', () => {
    const md = riskLandscapeToMarkdown(causes)
    expect(md).toContain('## 1. Heart Disease')
    expect(md).toContain('**APOE** (E3/E4)')
    expect(md).toContain('- [ ] **CONSIDER**: Statins discussion')
  })

  it('skips expansion for causes without genes', () => {
    const noCauses = [{ ...causes[0], genes: undefined, actions: undefined }]
    const md = riskLandscapeToMarkdown(noCauses)
    expect(md).not.toContain('## 1. Heart Disease')
  })
})

// ── geneToMarkdown ──────────────────────────────────────────────────────────

describe('geneToMarkdown', () => {
  const gene = {
    symbol: 'COMT', variant: 'Val158Met', rsid: 'rs4680',
    genotype: 'A/G', status: 'monitor', evidenceTier: 'E2',
    studyCount: 30, description: 'Intermediate COMT activity.',
  }
  const actions: ActionData[] = [{
    id: 'c1', type: 'monitor', title: 'Track stress response',
    description: 'Journal for 2 weeks.', evidenceTier: 'E2',
    studyCount: 10, tags: ['lifestyle'], geneSymbol: 'COMT', done: false,
  }]

  it('renders gene header fields', () => {
    const md = geneToMarkdown(gene, actions)
    expect(md).toContain('# Gene Report: COMT')
    expect(md).toContain('**Variant:** Val158Met')
    expect(md).toContain('**Genotype:** A/G')
  })

  it('renders actions section', () => {
    const md = geneToMarkdown(gene, actions)
    expect(md).toContain('- [ ] **MONITOR**: Track stress response')
  })

  it('skips actions heading when none exist', () => {
    const md = geneToMarkdown(gene, [])
    expect(md).not.toContain('## Actions')
  })
})

// ── checklistToMarkdown ─────────────────────────────────────────────────────

describe('checklistToMarkdown', () => {
  const items: ChecklistItem[] = [
    { id: '1', gene_symbol: 'MTHFR', action_type: 'consider', title: 'Take methylfolate', done: false, done_at: null, notes: null, practical_category: '', health_domain: '', created_at: '' },
    { id: '2', gene_symbol: 'custom', action_type: 'monitor', title: 'Daily meditation', done: true, done_at: '2026-01-10', notes: null, practical_category: '', health_domain: '', created_at: '' },
  ]

  it('separates pending and done sections', () => {
    const md = checklistToMarkdown(items)
    expect(md).toContain('## Pending')
    expect(md).toContain('## Done')
  })

  it('renders pending items with gene symbol', () => {
    const md = checklistToMarkdown(items)
    expect(md).toContain('- [ ] Take methylfolate (MTHFR)')
  })

  it('renders done items without gene for custom', () => {
    const md = checklistToMarkdown(items)
    expect(md).toContain('- [x] Daily meditation')
    expect(md).not.toContain('Daily meditation (custom)')
  })

  it('skips pending section when all done', () => {
    const allDone = items.map(i => ({ ...i, done: true }))
    const md = checklistToMarkdown(allDone)
    expect(md).not.toContain('## Pending')
  })
})

// ── addictionToMarkdown ─────────────────────────────────────────────────────

describe('addictionToMarkdown', () => {
  const pathways: PathwaySection[] = [{
    narrative: {
      pathway: 'Dopamine & Reward',
      status: 'actionable',
      body: 'Enhanced reward sensitivity.',
      priority: '1 actionable',
      hint: '',
      geneCount: 1,
      actionCount: 0,
    },
    genes: [{
      symbol: 'DRD2', variant: 'Taq1A', rsid: 'rs1800497',
      genotype: 'C/T', status: 'actionable', evidenceTier: 'E2',
      studyCount: 15, description: 'Reduced D2 receptor density.',
      actionCount: 0, categories: [], pathway: 'Dopamine & Reward',
    }],
  }]

  const substances = [{
    name: 'Alcohol',
    status: 'Caution',
    statusColor: 'var(--sig-risk)',
    borderColor: 'var(--sig-risk)',
    description: 'Altered metabolism detected.',
    genes: 'ADH1B, ALDH2',
    relevantEnzymes: ['ADH1B'],
    harmTitle: 'Harm reduction',
    harmText: 'Limit to 1-2 drinks; monitor flush response.',
  }]

  it('includes header', () => {
    const md = addictionToMarkdown(pathways, substances)
    expect(md).toContain('# Addiction & Reward Profile')
  })

  it('renders substance cards', () => {
    const md = addictionToMarkdown(pathways, substances)
    expect(md).toContain('### Alcohol')
    expect(md).toContain('**Harm reduction:** Limit to 1-2 drinks')
  })

  it('renders gene table', () => {
    const md = addictionToMarkdown(pathways, substances)
    expect(md).toContain('| DRD2 | Taq1A | C/T | actionable |')
  })
})

// ── Edge cases: special characters ─────────────────────────────────────────

describe('mentalHealthToMarkdown — special characters', () => {
  it('preserves special chars (& < > ") in gene descriptions', () => {
    const sections: PathwaySection[] = [{
      narrative: {
        pathway: 'Test',
        status: 'actionable',
        body: 'Body with & < > "quotes".',
        priority: '1 actionable',
        hint: '',
        geneCount: 1,
        actionCount: 0,
      },
      genes: [{
        symbol: 'GENE1', variant: 'A>T', rsid: 'rs123',
        genotype: 'A/T', status: 'actionable', evidenceTier: 'E2',
        studyCount: 1, description: 'Risk & benefit "balanced" <high>.',
        actionCount: 0, categories: ['mood'], pathway: 'Test',
      }],
    }]

    const md = mentalHealthToMarkdown(sections, {})
    expect(md).toContain('Body with & < > "quotes".')
    expect(md).toContain('Risk & benefit "balanced" <high>.')
    expect(md).toContain('A>T')
  })
})

describe('mentalHealthToMarkdown — empty actions list', () => {
  it('skips actions section when gene has no actions', () => {
    const sections: PathwaySection[] = [{
      narrative: {
        pathway: 'Empty',
        status: 'monitor',
        body: 'Nothing to do.',
        priority: '2 monitor',
        hint: '',
        geneCount: 1,
        actionCount: 0,
      },
      genes: [{
        symbol: 'COMT', variant: 'Val158Met', rsid: 'rs4680',
        genotype: 'A/G', status: 'monitor', evidenceTier: 'E3',
        studyCount: 5, description: 'Intermediate.',
        actionCount: 0, categories: ['mood'], pathway: 'Empty',
      }],
    }]

    const md = mentalHealthToMarkdown(sections, {})
    expect(md).not.toContain('### Actions for COMT')
  })

  it('skips actions section when actions record has empty array', () => {
    const sections: PathwaySection[] = [{
      narrative: {
        pathway: 'Empty',
        status: 'monitor',
        body: 'Nothing.',
        priority: '2 monitor',
        hint: '',
        geneCount: 1,
        actionCount: 0,
      },
      genes: [{
        symbol: 'COMT', variant: 'Val158Met', rsid: 'rs4680',
        genotype: 'A/G', status: 'monitor', evidenceTier: 'E3',
        studyCount: 5, description: 'Intermediate.',
        actionCount: 0, categories: ['mood'], pathway: 'Empty',
      }],
    }]

    const md = mentalHealthToMarkdown(sections, { COMT: [] })
    expect(md).not.toContain('### Actions for COMT')
  })
})

describe('mentalHealthToMarkdown — empty sections', () => {
  it('produces header-only output with no sections', () => {
    const md = mentalHealthToMarkdown([], {})
    expect(md).toContain('# Mental Health Genetic Profile')
    expect(md).toContain('2026-01-15')
    expect(md).toContain('Generated by Genome Toolkit')
    // No pathway headings
    expect(md).not.toContain('## ')
  })
})

// ── lifeMapToMarkdown ─────────────────────────────────────────────────────────

import { lifeMapToMarkdown } from '../lib/export'
import type { CountryAnchor, BlendMarker } from '../lib/lifeBlend'
import type { LifeModifier } from '../hooks/useLifeMap'

describe('lifeMapToMarkdown', () => {
  const anchors: CountryAnchor[] = [
    { country: 'RU', name: 'Russia', exAtAge: 14.2, targetAge: 74.2 },
    { country: 'DE', name: 'Germany', exAtAge: 41.5, targetAge: 79.5 },
  ]
  const blend: BlendMarker = { targetAge: 75.5, spread: { min: 74.2, max: 79.5 }, heuristic: true }
  const modifiers: LifeModifier[] = [
    { id: 'smoking', category: 'stress', label: 'Smoking', qualitative: 'Most studied factor', actions: [], evidence: 'strong', range: { lowYears: 5, highYears: 10 } },
    { id: 'anxiety', category: 'mental-health', label: 'Anxiety disorder', qualitative: 'Supportive note', actions: [], evidence: 'weak' },
  ]
  const input = {
    sex: 'male', age: 38, currentCountry: 'DE',
    anchors, residences: [{ country: 'RU', years: 33 }, { country: 'DE', years: 5 }],
    blend, modifiers, retrieved: '2026-05-30',
  }

  it('includes assumptions, the anchor table and years lived', () => {
    const md = lifeMapToMarkdown(input)
    expect(md).toContain('# Life Map')
    expect(md).toContain('male')
    expect(md).toContain('38')
    expect(md).toContain('Russia')
    expect(md).toContain('74.2')
    expect(md).toContain('| 33 |') // years lived in Russia
  })

  it('labels the blend a heuristic, never a prediction', () => {
    const md = lifeMapToMarkdown(input)
    expect(md).toMatch(/heuristic/i)
    expect(md).toMatch(/not a personal prediction/i)
  })

  it('lists modifiers qualitatively and NEVER exports year ranges', () => {
    const md = lifeMapToMarkdown(input)
    expect(md).toContain('Smoking')
    expect(md).toContain('Anxiety disorder')
    expect(md).not.toMatch(/5.?10 years/) // opt-in range must not leak into export
    expect(md).not.toContain('lowYears')
  })

  it('reports the biggest gap between anchors', () => {
    const md = lifeMapToMarkdown(input)
    expect(md).toMatch(/5\.3/) // 79.5 - 74.2
  })
})
