import type { PathwaySection, ActionData } from '../types/genomics'
import type { PGxEnzymeSection } from '../types/pgx'
import { EVIDENCE_SCOPE_LABELS, isPrescriberScope } from '../types/pgx'
import type { MortalityCause } from '../components/risk/RiskLandscape'
import type { SubstanceCard } from '../hooks/useAddictionData'
import type { ChecklistItem } from '../hooks/useChecklist'
import type { CountryAnchor, BlendMarker, Residence } from './lifeBlend'
import type { LifeModifier } from '../hooks/useLifeMap'

// ── Print ────────────────────────────────────────────────────────────────────

export function printPage(mode: 'doctor' | 'prescriber' | 'pdf') {
  document.body.setAttribute('data-print-mode', mode)
  window.print()
  document.body.removeAttribute('data-print-mode')
}

// ── File download ────────────────────────────────────────────────────────────

export function downloadFile(content: string, filename: string, mimeType = 'text/markdown') {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ── PDF export ──────────────────────────────────────────────────────────────

export async function exportPdf(
  markdown: string,
  reportType: 'pgx' | 'mental-health' | 'full',
  metadata?: { title?: string; date?: string },
): Promise<void> {
  const resp = await fetch('/api/export/pdf', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ markdown, report_type: reportType, metadata }),
  })
  if (!resp.ok) {
    const err = await resp.json().catch(() => ({ detail: 'PDF export failed' }))
    throw new Error(err.detail || 'PDF export failed')
  }
  const blob = await resp.blob()
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = resp.headers.get('content-disposition')?.match(/filename="(.+)"/)?.[1]
    || `genome-report-${reportType}-${new Date().toISOString().slice(0, 10)}.pdf`
  a.click()
  URL.revokeObjectURL(url)
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function today() {
  return new Date().toISOString().slice(0, 10)
}

function footer() {
  return `\n---\n_Generated by Genome Toolkit on ${today()}_\n`
}

// ── Mental Health Markdown ───────────────────────────────────────────────────

export function mentalHealthToMarkdown(
  sections: PathwaySection[],
  actions: Record<string, ActionData[]>,
): string {
  const lines: string[] = [
    `# Mental Health Genetic Profile`,
    `_Date: ${today()}_`,
    '',
  ]

  for (const section of sections) {
    lines.push(`## ${section.narrative.pathway}`)
    lines.push('')
    lines.push(section.narrative.body)
    lines.push('')

    if (section.genes.length > 0) {
      lines.push('| Gene | Variant | Genotype | Status | Evidence | Description |')
      lines.push('|------|---------|----------|--------|----------|-------------|')
      for (const g of section.genes) {
        lines.push(`| ${g.symbol} | ${g.variant} | ${g.genotype} | ${g.status} | ${g.evidenceTier} (${g.studyCount} sources) | ${g.description} |`)
      }
      lines.push('')
    }

    // Actions for genes in this section
    for (const gene of section.genes) {
      const geneActions = actions[gene.symbol]
      if (geneActions && geneActions.length > 0) {
        lines.push(`### Actions for ${gene.symbol}`)
        lines.push('')
        for (const a of geneActions) {
          const check = a.done ? '[x]' : '[ ]'
          lines.push(`- ${check} **${a.type.toUpperCase()}**: ${a.title}`)
          if (a.description) lines.push(`  ${a.description}`)
        }
        lines.push('')
      }
    }
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── PGx Markdown ─────────────────────────────────────────────────────────────

export function pgxToMarkdown(sections: PGxEnzymeSection[]): string {
  const lines: string[] = [
    `# PGx / Drug Metabolism Report`,
    `_Date: ${today()}_`,
    '',
    '> This report summarizes pharmacogenomic findings relevant to medication dosing.',
    '> Discuss all changes with your prescribing physician.',
    '',
  ]

  for (const section of sections) {
    const e = section.enzyme
    lines.push(`## ${e.symbol} — ${e.status.toUpperCase()} metabolizer`)
    lines.push(`**Genotype:** ${e.alleles}`)
    if (e.guideline) lines.push(`**Guideline:** ${e.guideline}`)
    lines.push('')
    lines.push(e.description)
    lines.push('')

    const renderDrug = (d: PGxEnzymeSection['drugs'][number]) => {
      const icon = d.impact === 'danger' ? '!!!' : d.impact === 'warn' ? '!!' : d.impact === 'adjust' ? '!' : '-'
      lines.push(`### ${icon} ${d.drugClass} [${d.impact.toUpperCase()}]`)
      lines.push(`**Status:** ${d.statusText}`)
      lines.push(`**Evidence scope:** ${EVIDENCE_SCOPE_LABELS[d.evidenceScope]}`)
      if (d.drugList) lines.push(`**Drugs affected:** ${d.drugList}`)
      lines.push('')
      lines.push(d.description)
      if (d.dangerNote) {
        lines.push('')
        lines.push(`> **WARNING:** ${d.dangerNote}`)
      }
      lines.push('')
    }

    if (section.drugs.length > 0) {
      // Only guideline/label scopes belong in the prescriber report body.
      const prescriberDrugs = section.drugs.filter((d) => isPrescriberScope(d.evidenceScope))
      const otherDrugs = section.drugs.filter((d) => !isPrescriberScope(d.evidenceScope))

      for (const d of prescriberDrugs) renderDrug(d)

      if (otherDrugs.length > 0) {
        // Keep harm-reduction / exploratory / PK content, but clearly segregate it
        // so it cannot read as a genotype-backed prescriber recommendation.
        lines.push('### Not genotype-backed dosing — not for prescribing')
        lines.push('> The items below are harm-reduction, pharmacokinetic, or research-only notes.')
        lines.push('> They are NOT backed by your genotype as specific doses and must not be treated as prescriber recommendations.')
        lines.push('')
        for (const d of otherDrugs) renderDrug(d)
      }
    }

    lines.push('---')
    lines.push('')
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── Risk Landscape Markdown ──────────────────────────────────────────────────

export function riskLandscapeToMarkdown(causes: MortalityCause[]): string {
  const lines: string[] = [
    `# Mortality & Risk Landscape`,
    `_Date: ${today()}_`,
    '',
    '| Rank | Cause | % of Deaths | Status | Genes |',
    '|------|-------|------------|--------|-------|',
  ]

  for (const c of causes) {
    lines.push(`| ${c.rank} | ${c.cause} | ${c.pct}% | ${c.status} | ${c.genesText} |`)
  }
  lines.push('')

  // Expanded detail for causes with genes/actions
  for (const c of causes) {
    if (!c.genes?.length && !c.actions?.length) continue
    lines.push(`## ${c.rank}. ${c.cause}`)
    lines.push('')
    if (c.narrative) {
      lines.push(c.narrative)
      lines.push('')
    }
    if (c.genes && c.genes.length > 0) {
      lines.push('**Genes:**')
      for (const g of c.genes) {
        lines.push(`- **${g.symbol}** (${g.variant}) -- ${g.evidenceTier} -- ${g.status}: ${g.description}`)
      }
      lines.push('')
    }
    if (c.actions && c.actions.length > 0) {
      lines.push('**Actions:**')
      for (const a of c.actions) {
        lines.push(`- [ ] **${a.type.toUpperCase()}**: ${a.text}`)
      }
      lines.push('')
    }
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── Addiction Profile Markdown ────────────────────────────────────────────────

export function addictionToMarkdown(
  pathways: PathwaySection[],
  substances: SubstanceCard[],
): string {
  const lines: string[] = [
    `# Addiction & Reward Profile`,
    `_Date: ${today()}_`,
    '',
  ]

  for (const section of pathways) {
    lines.push(`## ${section.narrative.pathway}`)
    lines.push('')
    lines.push(section.narrative.body)
    lines.push('')

    if (section.genes.length > 0) {
      lines.push('| Gene | Variant | Genotype | Status | Evidence | Description |')
      lines.push('|------|---------|----------|--------|----------|-------------|')
      for (const g of section.genes) {
        lines.push(`| ${g.symbol} | ${g.variant} | ${g.genotype} | ${g.status} | ${g.evidenceTier} (${g.studyCount} sources) | ${g.description} |`)
      }
      lines.push('')
    }
  }

  if (substances.length > 0) {
    lines.push(`## Substance-Specific Harm Reduction`)
    lines.push('')
    for (const s of substances) {
      lines.push(`### ${s.name}`)
      lines.push(`_Status: ${s.status}_`)
      lines.push('')
      lines.push(s.description)
      lines.push('')
      lines.push(`**${s.harmTitle}:** ${s.harmText}`)
      lines.push('')
      lines.push(`_Genes: ${s.genes}_`)
      lines.push('')
    }
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── Gene Detail Markdown ─────────────────────────────────────────────────────

export function geneToMarkdown(
  gene: { symbol: string; variant: string; rsid: string; genotype: string; status: string; evidenceTier: string; studyCount: number; description: string },
  actions: ActionData[],
): string {
  const lines: string[] = [
    `# Gene Report: ${gene.symbol}`,
    `_Date: ${today()}_`,
    '',
    `- **Variant:** ${gene.variant}`,
    `- **rsID:** ${gene.rsid}`,
    `- **Genotype:** ${gene.genotype}`,
    `- **Status:** ${gene.status}`,
    `- **Evidence:** ${gene.evidenceTier} (${gene.studyCount} sources)`,
    '',
    gene.description,
    '',
  ]

  if (actions.length > 0) {
    lines.push('## Actions')
    lines.push('')
    for (const a of actions) {
      const check = a.done ? '[x]' : '[ ]'
      lines.push(`- ${check} **${a.type.toUpperCase()}**: ${a.title}`)
      if (a.description) lines.push(`  ${a.description}`)
    }
    lines.push('')
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── Checklist Markdown ───────────────────────────────────────────────────────

export function checklistToMarkdown(items: ChecklistItem[]): string {
  const lines: string[] = [
    `# Action Checklist`,
    `_Date: ${today()}_`,
    '',
  ]

  const pending = items.filter(i => !i.done)
  const done = items.filter(i => i.done)

  if (pending.length > 0) {
    lines.push('## Pending')
    lines.push('')
    for (const item of pending) {
      const gene = item.gene_symbol !== 'custom' ? ` (${item.gene_symbol})` : ''
      lines.push(`- [ ] ${item.title}${gene}`)
    }
    lines.push('')
  }

  if (done.length > 0) {
    lines.push('## Done')
    lines.push('')
    for (const item of done) {
      const gene = item.gene_symbol !== 'custom' ? ` (${item.gene_symbol})` : ''
      lines.push(`- [x] ${item.title}${gene}`)
    }
    lines.push('')
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── Life Map Markdown ─────────────────────────────────────────────────────────

export interface LifeMapExportInput {
  sex: string
  age: number
  currentCountry: string
  anchors: CountryAnchor[]
  residences: Residence[]
  blend: BlendMarker | null
  modifiers: LifeModifier[]
  retrieved?: string
}

const MODIFIER_GROUPS: { key: LifeModifier['category']; label: string }[] = [
  { key: 'stress', label: 'Stress & lifestyle' },
  { key: 'mental-health', label: 'Mental health' },
  { key: 'family-history', label: 'Family history' },
]

export function lifeMapToMarkdown(input: LifeMapExportInput): string {
  const { sex, age, currentCountry, anchors, residences, blend, modifiers } = input
  const yearsBy = new Map(residences.map((r) => [r.country, r.years]))
  const currentName = anchors.find((a) => a.country === currentCountry)?.name ?? currentCountry

  const lines: string[] = [
    `# Life Map — Life Expectancy Context`,
    `_Date: ${today()}_`,
    '',
    `**Assumptions:** ${sex}, current age ${age}, current country ${currentName || '—'}.`,
    `These are **period life expectancy** figures (population statistics), **not a personal prediction**.`,
    '',
    `## Country anchors`,
    '',
    '| Country | Years lived | Life expectancy at age ' + age + ' | Expected age |',
    '|---------|------------|------|------|',
  ]
  for (const a of anchors) {
    lines.push(`| ${a.name} | ${yearsBy.get(a.country) ?? 0} | ${a.exAtAge.toFixed(1)} | ${a.targetAge.toFixed(1)} |`)
  }
  lines.push('')

  if (blend && anchors.length > 1) {
    const sorted = [...anchors].sort((x, y) => y.targetAge - x.targetAge)
    const gap = (sorted[0].targetAge - sorted[sorted.length - 1].targetAge).toFixed(1)
    const dominant = [...residences].sort((x, y) => y.years - x.years)[0]
    const dominantName = anchors.find((a) => a.country === dominant?.country)?.name ?? dominant?.country
    lines.push(`## Migration context marker`)
    lines.push('')
    lines.push(`Blended estimate **≈ ${blend.targetAge.toFixed(1)}** (spread ${blend.spread.min.toFixed(1)}–${blend.spread.max.toFixed(1)}).`)
    lines.push('')
    lines.push(`This is a **heuristic, not a personal prediction** — a years-lived blend weighted toward your current residence. Living across countries did **not** "cause" the gap; migration and mortality interact in complex ways (healthy-migrant effects, gradual risk convergence).`)
    lines.push('')
    lines.push(`- Biggest gap between anchors: **${gap} years** (${sorted[0].name} vs ${sorted[sorted.length - 1].name}).`)
    if (dominantName) lines.push(`- Most years lived in: **${dominantName}**.`)
    lines.push('')
  }

  const present = MODIFIER_GROUPS.filter((g) => modifiers.some((m) => m.category === g.key))
  if (present.length > 0) {
    lines.push(`## Life context`)
    lines.push('')
    lines.push(`_Qualitative factors only. Population year-range estimates are intentionally omitted from exports._`)
    lines.push('')
    for (const g of present) {
      lines.push(`### ${g.label}`)
      for (const m of modifiers.filter((x) => x.category === g.key)) {
        lines.push(`- **${m.label}** (evidence: ${m.evidence}) — ${m.qualitative.trim()}`)
      }
      lines.push('')
    }
  }

  if (input.retrieved) {
    lines.push(`_Data: Eurostat (EU) + WHO GHO (Russia), retrieved ${input.retrieved}._`)
  }
  lines.push(`_Not medical advice. For awareness and prevention, not diagnosis._`)
  lines.push(footer())
  return lines.join('\n')
}
